/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
<<<<<<< HEAD
  const ElMessage: typeof import('element-plus/es')['ElMessage']
=======
>>>>>>> 07dff4fdc73e08fe0c8932166dbaec08f3a2c982
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
}
