/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddModifyRoles: typeof import('./src/components/AddRoles/AddModifyRoles.vue')['default']
    AddtestDrawer: typeof import('./src/components/Databaselist/AddtestDrawer.vue')['default']
    AlladdQuestion: typeof import('./src/components/Databaselist/AlladdQuestion.vue')['default']
    AnswerSheet: typeof import('./src/components/AnswerSheet.vue')['default']
    BatchImport: typeof import('./src/components/BatchImport.vue')['default']
    CreatetestQuestions: typeof import('./src/components/CreatetestQuestions.vue')['default']
    DatabaseDetail: typeof import('./src/components/Databaselist/DatabaseDetail.vue')['default']
    Databaselists: typeof import('./src/components/Databaselist/Databaselists.vue')['default']
    EcharTs: typeof import('./src/components/EcharTs.vue')['default']
    Editor: typeof import('./src/components/Databaselist/Editor.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
<<<<<<< HEAD
=======
=======
<<<<<<< HEAD
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
=======
>>>>>>> 19b221c1bccc5f6e41918d0f7666ae1ebb9072f2
>>>>>>> 96147fa6555657c302a0194cb9d6d6e672a2a28f
>>>>>>> 76607b44eeb2ffc4356eaa43e3c565a5a97b4184
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTransfer: typeof import('element-plus/es')['ElTransfer']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExamDrawer: typeof import('./src/components/ExamsZu/ExamDrawer.vue')['default']
    ListtoftestView: typeof import('./src/components/ListtoftestView.vue')['default']
    QuestionBankLogView: typeof import('./src/components/QuestionBankLogView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemDrawer: typeof import('./src/components/SystemDrawer.vue')['default']
    SystemTransfer: typeof import('./src/components/SystemTransfer.vue')['default']
    TableangPage: typeof import('./src/components/TableangPage.vue')['default']
    TestAddWangEditor: typeof import('./src/components/TestAddWangEditor.vue')['default']
    TestDogis: typeof import('./src/components/TestDogis.vue')['default']
    TestExpor: typeof import('./src/components/TestExpor.vue')['default']
    TestpaperListView: typeof import('./src/components/TestpaperListView.vue')['default']
    TestquestiondetailsView: typeof import('./src/components/TestquestiondetailsView.vue')['default']
    TestStepsDialog: typeof import('./src/components/TestStepsDialog.vue')['default']
    TransFer: typeof import('./src/components/Databaselist/TransFer.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
